export enum JourneyStage {
  STARTED = 'STARTED',
  GOAL_IDENTIFIED = 'GOAL_IDENTIFIED',
  PROFILE_BUILDING = 'PROFILE_BUILDING',
  DOCUMENT_COLLECTION = 'DOCUMENT_COLLECTION',
  DOCUMENT_PROCESSING = 'DOCUMENT_PROCESSING',
  CLARIFICATION_REQUIRED = 'CLARIFICATION_REQUIRED',
  QUALIFICATION_PENDING = 'QUALIFICATION_PENDING',
  QUALIFICATION_COMPLETE = 'QUALIFICATION_COMPLETE',
  CONSULTANT_REVIEW = 'CONSULTANT_REVIEW',
  NEXT_STEP_READY = 'NEXT_STEP_READY',
  COMPLETED = 'COMPLETED',
}

export enum DocumentStatus {
  UPLOADED = 'uploaded',
  PROCESSING = 'processing',
  PROCESSED = 'processed',
  VERIFIED = 'verified',
  REJECTED = 'rejected',
  CONFLICT = 'conflict',
  FAILED = 'failed',
}

export enum ActionPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ActionStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DISMISSED = 'DISMISSED',
}

export enum ConversationChannel {
  WEB = 'WEB',
  TELEGRAM = 'TELEGRAM',
  WHATSAPP = 'WHATSAPP',
  VOICE = 'VOICE',
}

export enum MessageSender {
  APPLICANT = 'APPLICANT',
  AI = 'AI',
  CONSULTANT = 'CONSULTANT',
  SYSTEM = 'SYSTEM',
}

export enum QualificationStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  QUALIFIED = 'QUALIFIED',
  NOT_QUALIFIED = 'NOT_QUALIFIED',
  CONDITIONAL = 'CONDITIONAL',
}

export enum RequirementStatus {
  SATISFIED = 'SATISFIED',
  MISSING = 'MISSING',
  INCOMPLETE = 'INCOMPLETE',
  CONFLICT = 'CONFLICT',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum NextActionType {
  RESOLVE_CONFLICT = 'RESOLVE_CONFLICT',
  COMPLETE_PROFILE = 'COMPLETE_PROFILE',
  UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT',
  VERIFY_DOCUMENT = 'VERIFY_DOCUMENT',
  COMPLETE_REQUIREMENT = 'COMPLETE_REQUIREMENT',
  CONTACT_EDUCARO = 'CONTACT_EDUCARO',
  OPTIONAL_IMPROVEMENT = 'OPTIONAL_IMPROVEMENT',
  NO_ACTION = 'NO_ACTION',
}
